version: '3.9'
services:
  frontend:
    build: ./front-end
    ports:
    - 3000:3000
    volumes:
      - ./front-end:/app-frontend
    working_dir: /app-frontend
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'