version: '3.9'
services:
  frontend:
    build: ./front-end
    ports:
    - 3000:3000
    depends_on:
    - backend
    working_dir: /app-frontend
  backend:
    build: ./back-end
    ports:
    - 3001:3001
    working_dir: /app-backend
    command: dev
    volumes:
    - ./back-end/src:/app-backend/src
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senhaDoDB
      - MYSQL_DB_NAME=delivery-app
      - EVAL_ALWAYS_RESTORE_DEV_DB=true
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'